create_clock -period 20.000 -name sys_clk_pin [get_ports clk]

set_property PACKAGE_PIN J14 [get_ports clk]
set_property PACKAGE_PIN AC21 [get_ports cs_n_o]
set_property PACKAGE_PIN AF15 [get_ports miso_i]
set_property PACKAGE_PIN AB12 [get_ports mosi_o]
set_property PACKAGE_PIN H6 [get_ports rst_n]
set_property PACKAGE_PIN AD23 [get_ports sck_o]
set_property IOSTANDARD LVCMOS18 [get_ports clk]
set_property IOSTANDARD LVCMOS25 [get_ports cs_n_o]
set_property IOSTANDARD LVCMOS25 [get_ports miso_i]
set_property IOSTANDARD LVCMOS25 [get_ports mosi_o]
set_property IOSTANDARD LVCMOS25 [get_ports sck_o]
set_property IOSTANDARD LVCMOS15 [get_ports rst_n]
